# Generated by Django 5.2 on 2025-05-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_memorizationrecord_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorizationrecord',
            name='level',
            field=models.CharField(blank=True, choices=[('bad', 'Bad'), ('good', 'Good'), ('very_good', 'Very Good'), ('excellent', 'Excellent')], default='good', max_length=100, null=True, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='memorizationrecord',
            name='pages_memorized',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='pages memorized'),
        ),
        migrations.AlterField(
            model_name='memorizationrecord',
            name='surah',
            field=models.CharField(blank=True, help_text='Selected surahs (comma-separated)', max_length=1000, null=True, verbose_name='Surahs'),
        ),
    ]
